language: python
group: travis_latest
dist: xenial

git:
  depth: 25
  quiet: true

python:
- 3.8-dev
- 3.7

addons:
  apt:
    packages:
    - ffmpeg

install: pip install -e .

script:
- flake8
- mypy .
- pytest -v
