language: python
group: travis_latest
dist: xenial

git:
  depth: 25
  quiet: true

python:
- 3.8-dev
- 3.7

addons:
  apt:
    packages:
    - ffmpeg

matrix:
  include:
  - os: linux
    python: 3.7
    install: pip install -e .[tests]
    script:
    - flake8
    - mypy .

install: pip install -e .[tests]

script: pytest -v
