name: ci

on: [push, pull_request]

jobs:

  core:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.x']
        include:
        - os: ubuntu-latest
          python-version: '3.8'

    name: ${{ matrix.os }}-Python-${{ matrix.python-version }}

    steps:

    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - run: pip install .[tests,lint]
    - run: flake8
    - run: mypy

    - name: Install (windows)
      if: runner.os == 'Windows'
      run: cinst -y ffmpeg

    - name: Install (macos)
      if: runner.os == 'macOS'
      run: brew install ffmpeg

    - name: Install (linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt update
        sudo apt install --no-install-recommends ffmpeg

    - run: pytest
