name: ci

on: [push, pull_request]

jobs:

  linuxx:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.x']
    steps:
    - uses: actions/checkout@v2
    - name: Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - run: pip install .[tests,lint]
    - run: flake8
    - run: mypy .

    - run: sudo apt install -yq --no-install-recommends ffmpeg
    - run: pytest


  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - run: pip install .[tests]

    - run: brew install ffmpeg
    - run: pytest

  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - run: pip install .[tests]

    - run: cinst -y ffmpeg

    - run: pytest
