name: ci

on: [push, pull_request]

jobs:

  core:

    strategy:
      matrix:
        os: ['macos-latest', 'ubuntu-latest', 'windows-latest']
        python: ['3.7', '3.x']

    name: ${{ matrix.os }}-Python-${{ matrix.python }}

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}

    - run: pip install .[tests,lint]
    - run: flake8
    - run: mypy

    - name: Install
      if: runner.os == 'Windows'
      run: cinst -y ffmpeg

    - name: Install
      if: runner.os == 'macOS'
      run: brew install ffmpeg

    - name: Install
      if: runner.os == 'Linux'
      run: |
        sudo apt update -yq
        sudo apt install -yq --no-install-recommends ffmpeg

    - run: pytest
