name: ci

on: [push, pull_request]

jobs:

  core:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.13"]
        include:
        - os: ubuntu-latest
          python-version: '3.9'

    name: ${{ matrix.os }} Python ${{ matrix.python-version }}

    steps:

    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - run: pip install .[tests,lint]
    - run: flake8
    - run: mypy
# --- Windows
    - name: Install winget
      if: runner.os == 'Windows'
      uses: Cyberboss/install-winget@v1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: install prereqs (Windows)
      if: runner.os == 'Windows'
      run: winget install ffmpeg --disable-interactivity --accept-source-agreements

    - name: FFMPEG_ROOT Windows
      if: runner.os == 'Windows'
      run: echo "FFMPEG_ROOT=$env:LOCALAPPDATA/Microsoft/WinGet/Links/" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

# --- macOS
    - name: Install (macos)
      if: runner.os == 'macOS'
      run: brew install ffmpeg
# --- Linux
    - name: Install (linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt update
        sudo apt install --no-install-recommends ffmpeg

    - run: pytest
